# Generated by Django 4.2.2 on 2023-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_meme_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
